name = "co-op-compass"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "CARDS"
id = "fd0a944815424776a2e9ec8f5e61c840"
preview_id = "7b8c34d4371844d59debc1bca41271a7"